services:
  db:
    image: postgres
    restart: always
    container_name: cruchDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cruchDB
    ports:
      - "5432:5432"
    volumes:
      - cruch-data:/var/lib/postgresql/data

volumes:
  cruch-data:
